name = "hitung-cepat-worker"
main = "worker.js"
compatibility_date = "2024-05-18"

[vars]
APP_NAME = "Hitung Cepat"

[[d1_databases]]
binding = "DB_LATIHAN1"
database_name = "latihan1"
database_id = "2ec90a82-fa89-44bb-b82c-dca84f19ed36"

# Hapus atau komen bagian [site] dan [[routes]] yang berhubungan dengan public folder
# agar Worker ini hanya fokus pada API.
# Kemudian, deploy Worker ini secara terpisah.

# Jika Anda ingin Worker melayani API di subdomain workers.dev
# Anda tidak perlu bagian [[routes]] jika hanya menggunakan URL workers.dev default
# URL Anda akan menjadi hitung-cepat-worker.yourusername.workers.dev